CREATE TABLE IF NOT EXISTS perfil_permissoes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  perfil VARCHAR(40) NOT NULL,
  feature VARCHAR(80) NOT NULL,
  permitido BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_perfil_feature (perfil, feature)
);
